### ISSUE TITLE
Valoración de alquileres de zona de garaje

### ISSUE THREAD

**Issue by virolialo** [Aparking/AparKing_Backend#12]
Tarea perteneciente a la Épica [#7](https://github.com/Aparking/AparKing_Backend/issues/7)

El objetivo de esta tarea es que un usuario pueda poner una valoración a una oferta de alquiler de garaje.

**Comment by MarioArocaPaez** [comment]
Gente estoy con esto pero estoy teniendo problemas pa ejecutarlo pq esta rama no tiene lo del docker todavía sabeis que puedo hacer?


(isppvenv) PS C:\Users\mario\Desktop\UNI\ISPP\Workspace\AparKing_Backend> python manage.py makemigrations 
Traceback (most recent call last):
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\AparKing_Backend\manage.py", line 22, in <module>
    main()
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\AparKing_Backend\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\core\management\base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\core\management\commands\makemigrations.py", line 139, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\db\migrations\loader.py", line 58, in __init__
    self.build_graph()
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\db\migrations\loader.py", line 229, in build_graph
    self.load_disk()
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\db\migrations\loader.py", line 120, in load_disk
    migration_module = import_module(migration_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\AparKing_Backend\apps\parking\migrations\0001_initial.py", line 4, in <module>
    import django.contrib.gis.db.models.fields
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\contrib\gis\db\models\__init__.py", line 3, in <module>
    import django.contrib.gis.db.models.functions  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\contrib\gis\db\models\functions.py", line 3, in <module>
    from django.contrib.gis.db.models.fields import BaseSpatialField, GeometryField
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\contrib\gis\db\models\fields.py", line 3, in <module>
    from django.contrib.gis import forms, gdal
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\contrib\gis\forms\__init__.py", line 3, in <module>
    from .fields import (  # NOQA
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\contrib\gis\forms\fields.py", line 2, in <module>
    from django.contrib.gis.gdal import GDALException
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\contrib\gis\gdal\__init__.py", line 29, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\contrib\gis\gdal\datasource.py", line 41, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\contrib\gis\gdal\driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\contrib\gis\gdal\prototypes\ds.py", line 10, in <module>
    from django.contrib.gis.gdal.libgdal import lgdal
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\contrib\gis\gdal\libgdal.py", line 62, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal307", "gdal306", "gdal305", "gdal304", "gdal303", "gdal302", "gdal301", "gdal300", "gdal204"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
(isppvenv) PS C:\Users\mario\Desktop\UNI\ISPP\Workspace\AparKing_Backend>

**Comment by MarioArocaPaez** [comment]
Subo lo que he hecho por si le podéis echar un vistazo a si es lo que hay que hacer. Que no sé si lo he entendido bien

**Comment by 3ralon** [comment]
Cerrado como no planeado por reducción del alcance.
