### ISSUE TITLE
Realizar conjunto de pruebas de alquiler de garajes

### ISSUE THREAD

**Issue by virolialo** [Aparking/AparKing_Backend#13]
**Pendiente de concretar la información tras la planificación del Sprint 2**

**Comment by MarioArocaPaez** [comment]
He hecho unos cuantos tests, por ahora voy a dejarlo así porque creo que tenemos que centrarnos en acabar todo lo necesario para este sprint. Hay un problema y es que a la hora de ejecutarlos no sé por que si ejecutas todos los test del modulo da este error:
`(isppvenv) PS C:\Users\mario\Desktop\UNI\ISPP\Workspace\AparKing_Backend> python manage.py test apps.garagement
Traceback (most recent call last):
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\AparKing_Backend\manage.py", line 22, in <module>
    main()
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\AparKing_Backend\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\core\management\commands\test.py", line 24, in run_from_argv
    super().run_from_argv(argv)
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\core\management\commands\test.py", line 68, in handle
    failures = test_runner.run_tests(test_labels)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\test\runner.py", line 1054, in run_tests
    suite = self.build_suite(test_labels)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\test\runner.py", line 909, in build_suite
    tests = self.load_tests_for_label(label, discover_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mario\Desktop\UNI\ISPP\Workspace\isppvenv\Lib\site-packages\django\test\runner.py", line 890, in load_tests_for_label
    tests = self.test_loader.discover(start_dir=label, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\unittest\loader.py", line 316, in discover
    self._top_level_dir = self._get_directory_containing_module(top_part)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mario\AppData\Local\Programs\Python\Python311\Lib\unittest\loader.py", line 327, in _get_directory_containing_module
    full_path = os.path.abspath(module.__file__)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 573, in abspath
  File "<frozen ntpath>", line 540, in normpath
TypeError: expected str, bytes or os.PathLike object, not NoneType`

Así que ahora mismo solo se pueden ejecutar manualmente con cada archivo no sé muy bien por qué:

`(isppvenv) PS C:\Users\mario\Desktop\UNI\ISPP\Workspace\AparKing_Backend> python manage.py test apps.garagement.tests.test_urls
Found 1 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.
----------------------------------------------------------------------
Ran 1 test in 0.800s

OK
Destroying test database for alias 'default'...
(isppvenv) PS C:\Users\mario\Desktop\UNI\ISPP\Workspace\AparKing_Backend> python manage.py test apps.garagement.tests.test_views
Found 1 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.
----------------------------------------------------------------------
Ran 1 test in 0.751s

OK
Destroying test database for alias 'default'...
(isppvenv) PS C:\Users\mario\Desktop\UNI\ISPP\Workspace\AparKing_Backend> python manage.py test apps.garagement.tests.test_serializers
Found 1 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.
----------------------------------------------------------------------
Ran 1 test in 0.017s

OK
Destroying test database for alias 'default'...`

**Comment by JuanCarlosRL** [comment]
Ahora mismo para correr los test hay que ejecutar los archivos de forma individual, por ejemplo `python manage.py test apps/authentication/test` (indicando la carpeta en la que se encuentra el archivo tests.py) si intentas pasar todos los test a la vez no encuentra los archivos, es algo que se está viendo y buscando una solución
